description = "Core Configuration"
enableForceSensor = true
shellSensorPortName = "COM4"

# US Display Streaming Configuration
#USWindowDisplayName = "Galaxy Tab Active4 Pro 5G" # Using Phone Link
USWindowDisplayName = "SM-T638U" # Using scrcpy
USStreamDisplayName = "Ultrasound Stream"

# the path here is relative to the root of the project
DataPath = "\\ALIGN_PhantomData"