description = "Core Configuration"
enableForceSensor = false

# US Display Streaming Configuration
#USWindowDisplayName = "Galaxy Tab Active4 Pro 5G"
USWindowDisplayName = "Media Player"
USStreamDisplayName = "Ultrasound Stream"

# the path here is relative to the root of the project
DataPath = "\\ALIGN_PhantomData"